### PR TITLE
Add default command 'default' if command is missing

### PR DESCRIPTION
**Pull request by bkreider**
Simply add a default "default" to the CMD environment variable if it is missing.

### CODE REVIEW

**Comment by AlbertDeFusco** [comment]
I'm not certain this is going to work in a general sense. It will work, however if there is a command called `default` in the anaconda-project.yml file. (See #4 while waiting for a release of anaconda-project)

```yaml
commands:
  viz:
    unix: panel serve plot.py
    supports_http_options: true
  api:
    unix: tranquilizer cheese.py
    supports_http_options: true
  http:
    unix: python -m http.server 8086
    supports_http_options: false
```

Viz is the "implicit default" command that gets run with `anaconda-project run`. But, without providing a command name you cannot pass arguments like `--anaconda-project-port 8086`.

Notice, however that `anaconda-project list-commands` provides the commands in alphabetical order. It is impossible to determine the "implicit default".

```
>anaconda-project list-commands
Commands for project: /Users/adefusco/Development/AnacondaPlatform/Python3.7

Name  Description
====  ===========
api   tranquilizer cheese.py --port 8087
http  python -m http.server 8086
viz   panel serve plot.py

(base) adefusco@0565-adefusco:Python3.7>anaconda-project run default
Failed to execute 'default': No such file or directory
```

**Comment by bkreider** [comment]
I noticed that after testing this.  The description of run says that it will default to the the first command if none are given, but that clearly fails when passing options.

**Comment by AlbertDeFusco** [comment]
indeed that is quite unfortunate and I'm working on fixing that in anaconda-project.

**Comment by bkreider** [comment]
I think the feature for anaconda-project is to store the commands in an orderedDict and then run the first one when no command is specified.  Or have a special key like _DEFAULT_ that maps to the first command (or some ugly syntax like _CMD_[0] which would let you pick a command without knowing the names).

**Comment by AlbertDeFusco** [comment]
Right! I'm stuck at the argparse level setting the optional command name and then picking up an arbitrary collection of further arguments. Can you provide some help here?

https://github.com/Anaconda-Platform/anaconda-project/blob/31e52222932b87f027b12f1e90aa452062c23161/anaconda_project/internal/cli/main.py#L107

**Comment by AlbertDeFusco** [comment]
Well, maybe it's just better to allow `anaconda-project run default` to run the first command if no command named `default` exists. I'll set that up.

**Comment by AlbertDeFusco** [comment]
closing this in favor of #19

**Pull request closed without merging**
